image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: paper.css.aei.sh
  repo: paper.css
tasks:
- package: |
    cd $repo
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz